#!/bin/bash

ARGS="--param ../Labs/rmi-2122/C2-config.xml"
ARGS+=" --lab ../Labs/rmi-2122/C2-lab.xml"
ARGS+=" --grid ../Labs/rmi-2122/C2-grid.xml"
(cd simulator; ./simulator $ARGS --scoring 2) &

sleep 1

(cd Viewer; ./Viewer --autoconnect)

killall simulator

echo Bye
